spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}  # Usando a variável de ambiente com valor padrão 'sa'
    password: ${SPRING_DATASOURCE_PASSWORD:password}  # Usando a variável de ambiente com valor padrão 'password'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG