spring:

  jackson:
    time-zone: 'America/Sao_Paulo'

  application:
    name: Spring Boot 3.4.3 - Updated

  datasource:
    url: jdbc:postgresql://localhost:5432/rest
    username: rest
    password: 1010231010
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      uuid_function: gen_random_uuid()

microservices:
  document-retry:
    max-attempts: 3
    delay-in-ms: 5000

logging:
  level:
    br.com.pvprojects: INFO