spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:db/migration
    enabled: true
    placeholders:
      uuid_function: RANDOM_UUID()
    baseline-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG