spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
    baseline-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG