# Use a imagem base do OpenJDK
FROM openjdk:21-jdk-slim

# Baixe o H2 jar
RUN apt-get update && apt-get install -y curl && \
    curl -o /opt/h2.jar https://github.com/h2database/h2database/releases/download/version-2.3.232/h2-2.3.232.jar

# Exponha a porta 9092 do H2
EXPOSE 9092

# Comando para iniciar o H2
CMD java -cp /opt/h2.jar org.h2.tools.Server -tcp -tcpAllowOthers -web -webAllowOthers -ifNotExists