name: Build API

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Validate API
        uses: actions/checkout@v4

      - name: Set up Java 21 (Custom JDK)
        run: |
          curl -fsSL https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz -o jdk-21.tar.gz
          tar -xzf jdk-21.tar.gz
          sudo mv jdk-21 /opt/
          sudo update-alternatives --install /usr/bin/java java /opt/jdk-21/bin/java 1
          sudo update-alternatives --config java

      - name: Install Gradle
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 7.6 # Altere para a versão desejada do Gradle

      - name: Build the application
        run: gradle clean build

      - name: Run tests
        run: gradle test