name: Build API

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Validate API
        uses: actions/checkout@v3

      - name: Set up Java 21 (Custom JDK)
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install java 21.0.0-oracle # Instala a versão do JDK 21 do Oracle
          sdk use java 21.0.0-oracle  # Seleciona o JDK 21 como padrão

      - name: Install Gradle
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 7.6 # Altere para a versão desejada do Gradle

      - name: Build the application
        run: ./gradlew clean build

      - name: Run tests
        run: ./gradlew test